# Application Name
spring.application.name=bancodigital

# Server Configuration
server.port=8080

# Active Spring Profile
spring.profiles.active=dev

# Database Configuration (PostgreSQL on Neon)
spring.datasource.url=jdbc:postgresql://neondb_owner:npg_7jpKCLV3Fqwc@ep-purple-darkness-amape8w9-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_7jpKCLV3Fqwc
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA and Hibernate Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Connection Pool (HikariCP) Configuration for Neon
spring.datasource.hikari.keepaliveTime=20000

# Actuator Endpoints
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=always

# JWT Configuration
app.jwt.secret=${JWT_SECRET_KEY}
app.jwt.expiration=86400000

# JPA Auditing Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.data.jpa.repositories.bootstrap-mode=default

