# Base de datos - Neon PostgreSQL
spring.datasource.url=jdbc:postgresql://TU_HOST/TU_DB?sslmode=require&channelBinding=require
spring.datasource.username=TU_USUARIO
spring.datasource.password=TU_PASSWORD
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP
spring.datasource.hikari.keepalive-time=20000

# JWT
app.jwt.secret=${JWT_SECRET_KEY}
app.jwt.expiration=86400000

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Actuator
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=always